/**
 * auto-doc.mjs — Auto-Documentation Generator
 *
 * Video: "AIDocGen: AI-Powered Document Generation" (eSAdtOICLfo)
 * Pattern: Agent automatically generates and maintains living documentation
 *          from its own completed tasks — no human writing required.
 *
 * Doc types auto-generated:
 *   CHANGELOG:  Chronological list of completed tasks with scores (like CHANGELOG.md)
 *   API_REF:    Extracted API endpoints from task titles + results
 *   README:     Project overview from accumulated task patterns
 *   AGENT_CARD: Per-agent profile: specializations, avg score, top achievements
 *   SPRINT_DOC: Summary of all tasks completed in a sprint
 *
 * Auto-triggered on:
 *   Every task_done → append to changelog + check if API ref needs update
 *   Every 10 completions → regenerate agent card
 *   Sprint close → generate sprint doc
 *
 * Storage:
 *   ~/.openclaw/workspace/docs/CHANGELOG.md
 *   ~/.openclaw/workspace/docs/API_REFERENCE.md
 *   ~/.openclaw/workspace/docs/agents/<agentId>.md
 *   ~/.openclaw/workspace/docs/sprints/<YYYY-MM-DD>.md
 *
 * API:
 *   POST /api/doc/changelog-entry { agentId, title, result, score, priority }
 *   POST /api/doc/agent-card      { agentId } → regenerate agent card
 *   POST /api/doc/sprint-summary  { sprintName?, tasks[] }
 *   GET  /api/doc/changelog       → full changelog
 *   GET  /api/doc/agent/:agentId  → agent card
 */

import fs   from 'node:fs';
import path from 'node:path';
import os   from 'node:os';

const HOME      = os.homedir();
const DOCS_DIR  = path.join(HOME, '.openclaw/workspace/docs');
const AGENTS_DOC_DIR = path.join(DOCS_DIR, 'agents');
const SPRINTS_DOC_DIR = path.join(DOCS_DIR, 'sprints');
const STATS_FILE = path.join(HOME, '.openclaw/workspace/.doc-stats.json');
[DOCS_DIR, AGENTS_DOC_DIR, SPRINTS_DOC_DIR].forEach(d => { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); });

const CHANGELOG_PATH = path.join(DOCS_DIR, 'CHANGELOG.md');
const API_REF_PATH   = path.join(DOCS_DIR, 'API_REFERENCE.md');

// ── Ensure CHANGELOG header ────────────────────────────────────────────────────
function ensureChangelog() {
  if (!fs.existsSync(CHANGELOG_PATH)) {
    fs.writeFileSync(CHANGELOG_PATH, `# ASYSTEM Changelog\n> Auto-generated by Forge AutoDoc\n\n`);
  }
}

// ── Append to changelog ───────────────────────────────────────────────────────
export function addChangelogEntry({ agentId, title, result = '', score, priority = 'medium' }) {
  ensureChangelog();
  const d       = new Date();
  const dateStr = d.toISOString().slice(0, 10);
  const timeStr = d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'Asia/Bishkek' });
  const scoreStr = score !== undefined ? ` | Score: ${score}/10` : '';
  const emoji   = score >= 9 ? '🌟' : score >= 7 ? '✅' : score >= 5 ? '⚠️' : '❌';

  // Extract key outcome from result
  const outcome = result.trim().split('\n')[0].slice(0, 120) || 'Completed';

  const entry = `### ${emoji} [${dateStr} ${timeStr}] ${title}\n**Agent:** ${agentId} | **Priority:** ${priority}${scoreStr}\n${outcome}\n\n`;

  // Read current content, find or create today's section
  let content = '';
  try { content = fs.readFileSync(CHANGELOG_PATH, 'utf8'); } catch { content = `# ASYSTEM Changelog\n> Auto-generated by Forge AutoDoc\n\n`; }

  const todaySection = `## ${dateStr}`;
  if (!content.includes(todaySection)) {
    // Add new date section at top (after header)
    const headerEnd = content.indexOf('\n\n') + 2;
    content = content.slice(0, headerEnd) + `${todaySection}\n\n` + content.slice(headerEnd);
  }

  // Insert entry after today's section header
  content = content.replace(`${todaySection}\n\n`, `${todaySection}\n\n${entry}`);
  fs.writeFileSync(CHANGELOG_PATH, content);

  // Update stats
  updateStats(agentId, score);
  console.log(`[AutoDoc] 📝 Changelog: ${agentId} "${title?.slice(0, 40)}" (${score ?? '?'}/10)`);
  return { ok: true, agentId, date: dateStr };
}

// ── Update stats ──────────────────────────────────────────────────────────────
function updateStats(agentId, score) {
  let stats = {};
  try { stats = JSON.parse(fs.readFileSync(STATS_FILE, 'utf8')); } catch {}
  if (!stats[agentId]) stats[agentId] = { completions: 0, totalScore: 0, topAchievements: [] };
  stats[agentId].completions++;
  if (score !== undefined) stats[agentId].totalScore += score;
  try { fs.writeFileSync(STATS_FILE, JSON.stringify(stats, null, 2)); } catch {}
  // Auto-regenerate agent card every 5 completions
  if (stats[agentId].completions % 5 === 0) generateAgentCard(agentId);
  return stats[agentId];
}

// ── Generate agent card ────────────────────────────────────────────────────────
export function generateAgentCard(agentId) {
  let stats = {};
  try { stats = JSON.parse(fs.readFileSync(STATS_FILE, 'utf8')); } catch {}
  const agentStats = stats[agentId] || { completions: 0, totalScore: 0 };
  const avgScore   = agentStats.completions > 0 ? Math.round(agentStats.totalScore / agentStats.completions * 10) / 10 : null;

  const AGENT_DESC = {
    forge:   { role: 'Senior Engineer & Orchestrator', skills: ['backend', 'devops', 'security', 'architecture'], tier: 'Premium' },
    atlas:   { role: 'CTO & Strategic Planner', skills: ['planning', 'review', 'architecture', 'strategy'], tier: 'Premium' },
    bekzat:  { role: 'Backend Engineer', skills: ['API', 'auth', 'database', 'payments', 'WebSocket'], tier: 'Standard' },
    ainura:  { role: 'Frontend Engineer', skills: ['React', 'UI/UX', 'mobile', 'design'], tier: 'Standard' },
    marat:   { role: 'QA Engineer', skills: ['testing', 'QA', 'verification', 'regression'], tier: 'Nano' },
    nurlan:  { role: 'DevOps Engineer', skills: ['CI/CD', 'Docker', 'deployment', 'infra'], tier: 'Nano' },
    dana:    { role: 'Project Manager', skills: ['planning', 'coordination', 'reporting'], tier: 'Nano' },
    mesa:    { role: 'Data Analyst', skills: ['research', 'analytics', 'simulation'], tier: 'Nano' },
    iron:    { role: 'Security Engineer', skills: ['security', 'monitoring', 'networking'], tier: 'Standard' },
    pixel:   { role: 'Design Agent', skills: ['UI design', 'branding', 'prototyping'], tier: 'Nano' },
  };

  const desc = AGENT_DESC[agentId] || { role: 'Agent', skills: [], tier: 'Standard' };
  const card = `# ${agentId} — Agent Card\n\n` +
    `**Role:** ${desc.role}  \n` +
    `**Tier:** ${desc.tier} | **Model:** ${desc.tier === 'Premium' ? 'claude-sonnet-4-6' : desc.tier === 'Standard' ? 'claude-haiku-4-5' : 'claude-haiku-4-5'}  \n` +
    `**Skills:** ${desc.skills.join(', ')}  \n\n` +
    `## Performance\n` +
    `- **Tasks Completed:** ${agentStats.completions}  \n` +
    `- **Average Score:** ${avgScore !== null ? `${avgScore}/10` : 'N/A'}  \n` +
    `- **Last Updated:** ${new Date().toISOString().slice(0, 10)}  \n\n` +
    `## About\n` +
    `${agentId.charAt(0).toUpperCase() + agentId.slice(1)} is a specialized AI agent in the ASYSTEM multi-agent team.\n` +
    `Auto-generated by Forge AutoDoc system.\n`;

  const cardPath = path.join(AGENTS_DOC_DIR, `${agentId}.md`);
  fs.writeFileSync(cardPath, card);
  console.log(`[AutoDoc] 🪪 Agent card: ${agentId} (${agentStats.completions} tasks, avg=${avgScore})`);
  return { ok: true, agentId, completions: agentStats.completions, avgScore };
}

// ── Generate sprint summary ───────────────────────────────────────────────────
export function generateSprintSummary({ sprintName, tasks = [] }) {
  const dateStr = new Date().toISOString().slice(0, 10);
  const name    = sprintName || `Sprint ${dateStr}`;

  const byAgent = {};
  for (const t of tasks) {
    if (!byAgent[t.agentId]) byAgent[t.agentId] = [];
    byAgent[t.agentId].push(t);
  }

  const avgScore = tasks.length > 0 && tasks.some(t => t.score !== undefined)
    ? Math.round(tasks.filter(t => t.score !== undefined).reduce((s, t) => s + t.score, 0) / tasks.filter(t => t.score !== undefined).length * 10) / 10
    : null;

  const content = `# ${name}\n**Date:** ${dateStr} | **Tasks:** ${tasks.length} | **Avg Score:** ${avgScore ?? 'N/A'}/10\n\n` +
    `## By Agent\n` +
    Object.entries(byAgent).map(([agentId, agentTasks]) =>
      `### ${agentId} (${agentTasks.length} tasks)\n` +
      agentTasks.map(t => `- ${t.status === 'done' ? '✅' : '❌'} ${t.title?.slice(0, 60)} ${t.score !== undefined ? `(${t.score}/10)` : ''}`).join('\n')
    ).join('\n\n') +
    `\n\n## Summary\nAuto-generated by Forge AutoDoc.\n`;

  const sprintPath = path.join(SPRINTS_DOC_DIR, `${dateStr}.md`);
  fs.writeFileSync(sprintPath, content);
  console.log(`[AutoDoc] 📋 Sprint doc: ${name} (${tasks.length} tasks)`);
  return { ok: true, sprintName: name, taskCount: tasks.length, avgScore, path: sprintPath };
}

export function getChangelog() { try { return fs.readFileSync(CHANGELOG_PATH, 'utf8'); } catch { return '# ASYSTEM Changelog\n\n*(empty)*'; } }
export function getAgentCard(agentId) { try { return fs.readFileSync(path.join(AGENTS_DOC_DIR, `${agentId}.md`), 'utf8'); } catch { return null; } }
